version: '2'
services:
  user_task_api:
    build:
      context: ./user-task-service
    container_name: "user-task-api"
    restart: always
    image: user-task-api:latest
    ports:
      - 9080:8080
  user_task_ui:
    build:
      context: ./user-task-ui
    container_name: "user-task-ui"
    image: user-task-ui:latest
    ports:
      - 9000:80
